server:
    port: 8000

service:
    host: 0.0.0.0

spring:
    application:
        name: apigateway-service
    cloud:
        gateway:
            default-filters:
                - 
                    name: GlobalFilter
                    args:
                        baseMessage: Got Filter
            routes:
                - 
                    id: first-service
                    uri: http://${service.host}:9000/
                    predicates:
                        - Path=/**
                    # filters:
                        # - RewritePath=/poemnote/(?<segment>.*), /$\{segment}
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                        - GET, POST, DELETE, PUT

